spring:
  application:
    name: ${SPRING_APPLICATION_NAME:securedbank-api}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  config:
    import:
      - classpath:application-prod.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5434}/${DATABASE_NAME:securedbank}}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:5}
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:20} # 20 connections
      idle-timeout: ${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT:600000} # 10 minutes#
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000} # 30 seconds
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false

  security:
    user:
      name: ${SECURITY_USERNAME:eazybytes}
      password: ${SECURITY_PASSWORD:12345}
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8180/realms/securedbank-api/protocol/openid-connect/certs}


  logging:
    level:
      org:
        springframework:
          security: ${SPRING_SECURITY_LOG_LEVEL:DEBUG}
      com:
        zaxxer:
          hikari:
            pool:
              HikariPool: DEBUG
    pattern:
      console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_only
      enabled: false
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:15m}

management:
  endpoint:
    health:
      show-details: always
    configprops:
      show-values: always
    env:
      show-values: always
  endpoints:
    web:
      exposure:
        include: "*"
  # to enable /actuator/info info prefix below is required
  info:
    env:
      enabled: ${MANAGEMENT_INFO_ENV_ENABLED:true}