CREATE TABLE customer
(
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(100) NOT NULL,
    mobile_number VARCHAR(20)  NOT NULL,
    pwd           VARCHAR(500) NOT NULL,
    role          VARCHAR(100) NOT NULL,
    create_dt     DATE DEFAULT NULL
);

CREATE TABLE accounts
(
    customer_id    BIGINT       NOT NULL,
    account_number BIGINT       NOT NULL,
    account_type   VARCHAR(100) NOT NULL,
    branch_address VARCHAR(200) NOT NULL,
    create_dt      DATE DEFAULT NULL,
    PRIMARY KEY (account_number),
    CONSTRAINT customer_ibfk_1 FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

CREATE INDEX accounts_customer_id_idx ON accounts (customer_id);

CREATE TABLE account_transactions
(
    transaction_id      VARCHAR(200) NOT NULL,
    account_number      BIGINT       NOT NULL,
    customer_id         BIGINT       NOT NULL,
    transaction_dt      DATE         NOT NULL,
    transaction_summary VARCHAR(200) NOT NULL,
    transaction_type    VARCHAR(100) NOT NULL,
    transaction_amt     INT          NOT NULL,
    closing_balance     INT          NOT NULL,
    create_dt           DATE DEFAULT NULL,
    PRIMARY KEY (transaction_id),
    CONSTRAINT accounts_ibfk_2 FOREIGN KEY (account_number) REFERENCES accounts (account_number) ON DELETE CASCADE,
    CONSTRAINT acct_user_ibfk_1 FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

CREATE INDEX account_transactions_customer_id_idx ON account_transactions (customer_id);
CREATE INDEX account_transactions_account_number_idx ON account_transactions (account_number);

CREATE TABLE loans
(
    loan_number        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id        BIGINT       NOT NULL,
    start_dt           DATE         NOT NULL,
    loan_type          VARCHAR(100) NOT NULL,
    total_loan         INT          NOT NULL,
    amount_paid        INT          NOT NULL,
    outstanding_amount INT          NOT NULL,
    create_dt          DATE DEFAULT NULL,
    CONSTRAINT loan_customer_ibfk_1 FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

CREATE INDEX loans_customer_id_idx ON loans (customer_id);

CREATE TABLE cards
(
    card_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_number      VARCHAR(100) NOT NULL,
    customer_id      BIGINT       NOT NULL,
    card_type        VARCHAR(100) NOT NULL,
    total_limit      INT          NOT NULL,
    amount_used      INT          NOT NULL,
    available_amount INT          NOT NULL,
    create_dt        DATE DEFAULT NULL,
    CONSTRAINT card_customer_ibfk_1 FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

CREATE INDEX cards_customer_id_idx ON cards (customer_id);

CREATE TABLE notice_details
(
    notice_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_summary VARCHAR(200) NOT NULL,
    notice_details VARCHAR(500) NOT NULL,
    notic_beg_dt   DATE         NOT NULL,
    notic_end_dt   DATE DEFAULT NULL,
    create_dt      DATE DEFAULT NULL,
    update_dt      DATE DEFAULT NULL
);

CREATE TABLE contact_messages
(
    contact_id    VARCHAR(50)   NOT NULL,
    contact_name  VARCHAR(50)   NOT NULL,
    contact_email VARCHAR(100)  NOT NULL,
    subject       VARCHAR(500)  NOT NULL,
    message       VARCHAR(2000) NOT NULL,
    create_dt     DATE DEFAULT NULL,
    PRIMARY KEY (contact_id)
);
