-- Flyway V1: PostgreSQL schema + seed data
-- Converted from MySQL (AUTO_INCREMENT → IDENTITY, INSERT IGNORE → ON CONFLICT)

CREATE TABLE users
(
    username VARCHAR(50)  NOT NULL PRIMARY KEY,
    password VARCHAR(500) NOT NULL,
    enabled  BOOLEAN      NOT NULL
);

CREATE TABLE authorities
(
    username  VARCHAR(50) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_authorities_users
        FOREIGN KEY (username) REFERENCES users (username)
);

CREATE UNIQUE INDEX ix_auth_username ON authorities (username, authority);

INSERT INTO users (username, password, enabled)
VALUES ('user', '{noop}EazyBytes@12345', TRUE),
       ('admin', '{bcrypt}$2a$12$88.f6upbBvy0okEa7OfHFuorV29qeK.sVbB9VQ6J6dWM1bW6Qef8m', TRUE)
ON CONFLICT (username) DO NOTHING;

INSERT INTO authorities (username, authority)
VALUES ('user', 'read'),
       ('admin', 'admin')
ON CONFLICT (username, authority) DO NOTHING;

CREATE TABLE customer
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(45)  NOT NULL,
    pwd   VARCHAR(200) NOT NULL,
    role  VARCHAR(45)  NOT NULL
);

INSERT INTO customer (email, pwd, role)
VALUES ('happy@example.com', '{noop}EazyBytes@12345', 'read'),
       ('admin@example.com', '{bcrypt}$2a$12$88.f6upbBvy0okEa7OfHFuorV29qeK.sVbB9VQ6J6dWM1bW6Qef8m', 'admin');
