-- Flyway V1 migration: PostgreSQL 16 compatible
-- Use IDENTITY columns and idempotent seed data

-- Note: avoid CREATE INDEX CONCURRENTLY inside a transaction. If you need CONCURRENTLY, put it in a separate migration and set executeInTransaction=false for that migration.

CREATE TABLE IF NOT EXISTS users (
  username VARCHAR(50) PRIMARY KEY,
  password VARCHAR(500) NOT NULL,
  enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS authorities (
  username VARCHAR(50) NOT NULL,
  authority VARCHAR(50) NOT NULL,
  CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE,
  CONSTRAINT uq_authorities_username_authority UNIQUE (username, authority)
);

CREATE TABLE IF NOT EXISTS customer (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  pwd VARCHAR(200) NOT NULL,
  role VARCHAR(45) NOT NULL,
  CONSTRAINT uq_customer_email UNIQUE (email)
);

-- Seed data (idempotent)
INSERT INTO users (username, password, enabled) VALUES
  ('user', '{noop}EazyBytes@12345', TRUE)
ON CONFLICT (username) DO NOTHING;

INSERT INTO authorities (username, authority) VALUES
  ('user', 'read')
ON CONFLICT (username, authority) DO NOTHING;

INSERT INTO users (username, password, enabled) VALUES
  ('admin', '{bcrypt}$2a$12$88.f6upbBvy0okEa7OfHFuorV29qeK.sVbB9VQ6J6dWM1bW6Qef8m', TRUE)
ON CONFLICT (username) DO NOTHING;

INSERT INTO authorities (username, authority) VALUES
  ('admin', 'admin')
ON CONFLICT (username, authority) DO NOTHING;

INSERT INTO customer (email, pwd, role) VALUES
  ('happy@example.com', '{noop}EazyBytes@12345', 'read')
ON CONFLICT (email) DO NOTHING;

INSERT INTO customer (email, pwd, role) VALUES
  ('admin@example.com', '{bcrypt}$2a$12$88.f6upbBvy0okEa7OfHFuorV29qeK.sVbB9VQ6J6dWM1bW6Qef8m', 'admin')
ON CONFLICT (email) DO NOTHING;
