CREATE TABLE authorities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT authorities_ibfk_1 FOREIGN KEY (customer_id) REFERENCES customer (customer_id)
);

CREATE INDEX authorities_customer_id_idx ON authorities (customer_id);

-- INSERT INTO authorities (customer_id, name) VALUES (1, 'VIEWACCOUNT');
-- INSERT INTO authorities (customer_id, name) VALUES (1, 'VIEWCARDS');
-- INSERT INTO authorities (customer_id, name) VALUES (1, 'VIEWLOANS');
-- INSERT INTO authorities (customer_id, name) VALUES (1, 'VIEWBALANCE');
--
-- DELETE FROM authorities;

INSERT INTO authorities (customer_id, name) VALUES (1, 'ROLE_USER');
INSERT INTO authorities (customer_id, name) VALUES (1, 'ROLE_ADMIN');
